### ISSUE TITLE
Export voice notes

### ISSUE THREAD

**Issue by rudolfbyker** [IdealChain/signal-media-exporter#10]
Are voice notes not considered media in signal? I see that these audio clips are not included under "media" in the signal app, nor are they exported by this project. I would love to be able to export all audio clips from a chat.

**Comment by IdealChain** [comment]
Good question, I don't normally use them. I suppose it's just a problem with our query since we only select for "hasVisualAttachments", but voice messages have only "hasAttachments" set and a flag identifying it as voice message.

It should be rather easy to export them when I find a bit of time - I'm just not sure if everybody wants to include them, so better introduce an optional command line flag / config setting, too.
